name: yolov8
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  - pytorch-cuda=11.8 # Change it depend on your setup
  - pip
  - pip:
      - ultralytics
