name: yolov8
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - pytorch
  - torchvision
  # Remove the next line to use pytorch CPU
  - pytorch-cuda=11.8
  - pip
  - pip:
      - ultralytics
